### ISSUE TITLE
Check user guide is up to date

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1312]
Check through the user guide.

Is it still up to date enough to complete the example?

Do any of the screen shots need updating.

**Comment by rbauststfc** [comment]
I've had a look through the user guide and it still seems fine for completing the example. The following might be worth updating/improving at some point, though:

**Page: [User Guide](https://mantidproject.github.io/mantidimaging/user_guide/index.html)**

_Loading Sample Stack_

- In the instructions for loading the test data there's a reference to the "Tilt 4 pre preco" data set, however I can't see this name anywhere in the directory structure for the Flowers data.

_Project Window_

- The screenshot of the main window doesn't show the tree view. The current version of MI doesn't allow the tree view to be collapsed, so the view shown isn't achievable and might be good to update.

_Reconstruction_

- Would it be worth mentioning that beam hardening corrections can now be applied, with a link to a slightly more detailed explanation on a separate page?

- I think it might also be good to mention that automatic preview can be switched off. There's an explanation about this feature on the Operations Window page, so the same text could probably be copied across.

**Page: [Loading and Saving](https://mantidproject.github.io/mantidimaging/user_guide/gui/loading_saving.html#loading-and-saving)**

- Add sections to explain the "Load log for stack" and "Load projection angles" options on the File menu.

_180 Degree Projections_

- Add instructions for loading 180 projections to a dataset using the File menu option. Explain that this can only be done for stacks loaded via "Load dataset" (and "Load NeXus file"?), not "Load images".

_Saving_

- The screenshot of the Save dialog is technically out of date because float32 is now the default Pixel bit depth. We could consider updating this while we're making other changes to the page.

**Page: [Operations Window](https://mantidproject.github.io/mantidimaging/user_guide/gui/operations_window.html#operations-window)**

- The screenshot of the Operations window includes "Legend" and "Combine histograms" checkboxes at the top, which are no longer available. The descriptions provided in the documentation for these checkboxes, below the screenshot, should also be removed.
