### ISSUE TITLE
MIMiniImageView call add_auto_color_menu_action from the constructor

### ISSUE THREAD

**Issue by samtygier-stfc** [mantidproject/mantidimaging#1363]
### Desired Behaviour

`MIImageView` calls `self.add_auto_color_menu_action()` in its constructor.

In `MIMiniImageView`, this is currently not done, because `add_auto_color_menu_action()` needs to be passed the parent window.

If there is a simple way to allow calling it from the `MIMiniImageView` constructor that would be preferable, because it simplifies the interface and makes sure that any new instance gets an auto colour menu item.

**Comment by rbauststfc** [comment]
Looking again at this, another reason for not calling it in the constructor was because not all of the MIMiniImageViews currently offer the menu - only the recon preview image offers it of the three in the Reconstruction window, and the option isn't available for the images in the COR Inspection dialog. Is this just an oversight and we actually want the menu available for all of these as well?

**Comment by samtygier-stfc** [comment]
In that case lets add it everywhere.
