### ISSUE TITLE
Improve start-up time of application

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantidimaging#1588]
The application is slow to start up, particularly on IDAaaS. Initial investigations suggest this is due to a couple of things:

- Time taken for imports. This can take 30 seconds when starting without any cached imports, which possibly explains why we see particularly poor performance on IDAaaS. Once imports have been cached this takes between 2 and 8 seconds depending on platform (much slower on Windows). I found a command that can be run to see the time taken by imports - `python -X importtime -m mantidimaging`, however I found it tricky to spot anything because of the sheer number of imports that are output. Looking into this previously, it seemed to be the quantity of imports rather than any particularly slow ones that looked like the problem, but it would benefit from further investigation. An obvious first step would be to tidy up any imports that are needed only for type checking.

- Time taken to run the version check query in a shell subprocess (run in `_retrieve_conda_installed_version` in utility/version_check.py). This takes approximately 9 seconds on my Windows machine and 2.5 seconds on my Linux machine.

**Comment by rbauststfc** [comment]
I've experimented with adding `from __future__ import annotations` to all files to try and prevent imports that are purely for type checking from slowing the start-up time, however this didn't have any impact on import time on Windows.

**Comment by samtygier-stfc** [comment]
I have checked on  IDAaaS and the `__pycache__` files are already created on a fresh instance. These must be being created at install time, and so are not contributing to first start up time.

**Comment by samtygier-stfc** [comment]
To see whats happening with import times.
Disable multiprocessing in `mantidimaging/core/parallel/manager.py` by returning immediately in create_and_start_pool
```diff
 def create_and_start_pool():
+    return
     LOG.info('Creating process pool')
```
Record a trace by starting MI with
`python -X importtime -m mantidimaging 2> import_time.log`
and then close it. Plot with
`tuna import_time.log`

![image](https://user-images.githubusercontent.com/74248560/194032358-3ede8279-4ddf-407e-a957-6460a7c79a50.png)

The biggest easy win I see is that we spend 18% of the time importing matplotlib, because skimage.io has a matplotlib plugin. Best solution seems to be moving away from skimage.io #1203

**Comment by samtygier-stfc** [comment]
#1655 removes the call to `conda` to get the version, reducing startup tiime on my laptop form 5.3 to 1.9 seconds.
