### ISSUE TITLE
Change ROI parameter for filters to be on-user-request

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#349]
Filters that need ROI should use a ROI widget that will retrieve and display the ROI on the preview windows. The ROI widget will be responsible for communicating with the stack visualiser to retrieve the ROI. Current filters that do that are ROI normalisation and cropping.

The current behaviour will take the current ROI off the stack when the filter is applied. The new behaviour should present a button to retrieve the ROI. Afterwards that ROI will not change, regardless of whether the user moves it.

----------

Potentially this could help #502 by making Crop take a List of ROI's, and output multiple stacks

**Comment by WHTaylor** [comment]
Couple of things I wanted to clarify. As far as I understand, this issue is to implement:
- For all filters that require an ROI, show an ROI widget on the 'before' preview.
- The ROI should be selectable with either the preview ROI, or the one on the main SV

Could it be an option to have a 'lock' for the ROI parameters for the filter, rather than the button mentioned?

Is it part of the plan to, and does this need to wait till after, replacing the matplotlib plots (with a pyqtgraph ImageView)?

**Comment by DTasev** [comment]
It should get the ROI only from the main stack visualiser. My original idea was when the user clicks the ROI is set/locked for that filter, and moving the region afterwards will not change the parameters, unless the button is clicked again. 

Setting the ROI would have to update the preview as well. This shouldn't be tied to the matplotlib plots at all so I don't think that is an issue
