### ISSUE TITLE
Parallel module can't run in parallel

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#716]
Because the multiprocessing we use shares a global object across processes it has the limitation that running _two_ async parallel processing will have a guaranteed clash, as each one will change the shared data variable and cause some exception in the other.

Solution with `SharedArray`: because each array has a unique identifier, we can instead use this to get a handle to the data during processing.

Other solutions would probably require moving away from `SharedArray` completely, but as Python multiprocessing seems to be notoriously annoying to do, may have different drawbacks (i.e. if shared over a socket it may be slower).

**Comment by samtygier-stfc** [comment]
There are 2 options for this. One is to prevent the GUI from being able to start more than one operation on the data at a time. The other is to make it safe to run multiple operations at the same time (though only on separate datasets).

For now I think the first approach is best. While an operation is running, the GUI should not allow starting another. This is mostly fixed by #882 . Now the apply buttons in the operations window are disabled while a filter is running. The remaining work would be to stop a recon running at the same time that an operation was.
