### ISSUE TITLE
Consider `tomopy` removal, and instead integration of ASTRA CPU algorithms as replacement

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#765]
`tomopy` is a pretty big package dependency, and the only thing we use from it is `gridrec`. As it doesn't seem like `gridrec` is widely used for publishing, it might make more sense to drop it and instead integrate the ASTRA CPU algorithms.

This should make package building and installation smaller, with a small benefit of code cleanup.

**Comment by samtygier-stfc** [comment]
Looking at where Tomopy is currently used, removing it would be a big job. I think it is useful that it is possible reconstruct without a GPU even it is too slow for general use, so we should keep gridrec.

Operations

- circ mask
- stripe removal
- ring removal


Recon:

- gridrec - Needed because works on CPU

**Comment by dtasev** [comment]
It might be feasible to replace gridrec with FBP CPU implementation from ASTRA, it should be fairly straightforward (iirc just change the astra projector from `'cuda'` to `'line'` and algorithm `FBP_CUDA` to `FBP`). Performance wise it's likely that gridrec is still a lot faster than FBP on CPU.

For the operations I think circular mask we can easily reimplement, but stripe removal we'd need to compare it to the SarePy methods first, and similar for ring removal.

Perhaps this can be looked at again once we start looking at merging in CCPi methods
