### ISSUE TITLE
Create DOI for 2.0

### ISSUE THREAD

**Issue by dtasev** [mantidproject/mantidimaging#789]

**Comment by samtygier-stfc** [comment]
I've used https://zenodo.org/ for this before. It gives a DOI for each release plus one for all versions. E.g. https://doi.org/10.5281/zenodo.2598428 . Its free to use and makes a permanent archive of the software on CERN's infrastructure. It can either be connected to github to create a DOI automatically for each release, or we can just upload a tar.gz manually.

Otherwise it looks like Mantid use an STFC DOI, 10.5286/SOFTWARE/MANTID

**Comment by dtasev** [comment]
Thanks for this. I'll bring it up in the standup today to see whether we want to use an STFC one or if Zenodo is fine
